import Head from 'next/head'
import { Inter } from '@next/font/google'
import Header from '../components/Header'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  return (
    <div className='bg-black w-screen h-screen'>
      <Head>
        <title>PersonalProfile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </div>
  )
}
