import Head from 'next/head'
import { Inter } from '@next/font/google'
import Header from '../components/Header'
import Card from '../components/Card'
import Button from '../components/Button'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  return (
    <div className='bg-black w-screen h-screen'>
      <Head>
        <title>PersonalProfile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex w-screen'>
          <ul className='w-full h-16 max-h-16 pr-32 pl-32 mt-28 mb-8 flex flex-row text-white justify-between text-center items-center bg-blue-600'>
            <Header redirect={false}  url='/'>Adriel Bolandini</Header>
            <Header redirect={true}  url='http://www.linkedin.com/in/adrielbolandini'>Linkedin</Header>
            <Header redirect={true}  url='http://www.github.com/adrielbolandini'>GitHub</Header>
          </ul>
        </div>
      <div className='flex flex-row place-content-between'>
        <Card />
        <Button fnctOnClick={()=>{}}/>
      </div>
      
    </div>
  )
}
